# This will run on Travis' 'new' container-based infrastructure
sudo: false

language: python

python:
  - "2.7"
  - "3.5"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

# command to install dependencies
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION sphinx pip nose
    - pip install --user travis-sphinx
    - pip install -r requirements.txt
    - python setup.py install

# command to run tests
script:
    - nosetests --with-coverage --cover-erase --cover-html --cover-package=pygraphml
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then travis-sphinx --source=doc/source/ build; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then travis-sphinx deploy; fi
    - codeclimate-test-reporter
    - coverage xml
    - python-codacy-coverage -r coverage.xml




#     # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
#     # - sudo rm -rf /dev/shm
#     # - sudo ln -s /run/shm /dev/shm
